-- =============================================================================
-- PiedraAzul — datos de prueba (PostgreSQL)
-- =============================================================================
-- JPA crea el esquema (ddl-auto=update). Este script corre SOLO al crear
-- el volumen por primera vez.
--
-- Núcleo (01): sin tablas propias (enums VARCHAR, TimeRange TIME embeddable).
-- Personas (03): tablas especialidades, medicos, pacientes.
--
-- Descomenta los INSERTs cuando quieras datos iniciales (después del primer
-- arranque del backend, o crea las tablas manualmente antes).
--
-- INSERT INTO especialidades (nombre, activa) VALUES ('Medicina General', TRUE);
-- INSERT INTO especialidades (nombre, activa) VALUES ('Fisioterapia', TRUE);
-- INSERT INTO medicos (nombre_completo, especialidad_id, activo)
--   VALUES ('Dra. Ana Pérez', 1, TRUE);
-- INSERT INTO pacientes (usuario_id, nombre_completo, telefono)
--   VALUES (1, 'Juan Paciente', '3001234567');
--
-- Reinicializar volumen: docker compose down -v
-- =============================================================================
